"""Add firebase id

Revision ID: c4062d14de84
Revises: bd697b19b113
Create Date: 2022-05-13 20:42:28.016086

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4062d14de84'
down_revision = 'bd697b19b113'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('firebase_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_users_firebase_id'), 'users', ['firebase_id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_firebase_id'), table_name='users')
    op.drop_column('users', 'firebase_id')
    # ### end Alembic commands ###
